name: Next.js with Prisma + Stack Auth + Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build, Test, and Prepare Deployment
    runs_on: ubuntu-lastest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy

      - name: Build Next.js
        run: npm run build
